# -*- coding: utf-8 -*-
"""Cellular Automata 1D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17fmIGwqZ2pLjynjuwLT8TMzVj7xa38ub
"""

states=[0,1,1,0,1,0,1,0,0,0] # Seed (Generation at t=0)#cell 0 and 8 are to avoid IndexError
new_states=[0,0,0,0,0,0,0,0,0,0] #cello 0 and 8 are to avoid IndexError

days=6 #no of generations

#print ("t=0->",states,sep='') #sep='' remove default space between arguments
for n in range(days): #loop for no of generations
  print ("t=",n+1,"->",states,sep='')
  for i in range(1,9): #loop to check neighbours
    if (states[i+1] == states[i-1]): #XOR LOGIC if neighbours are equal cell dies
      new_states[i]=0
    else:
      new_states[i]=1
      
  #print ("t=",n+1,"->",new_states,sep='')
  states=new_states.copy()